### ISSUE TITLE
Solution Link in Readme is Wrong

### ISSUE THREAD

**Issue by rajat19** [Nullifiers/Hackerrank-Solution-Crawler#16]
**Bug**
Readme's generated do not contain valid solution links (path is incorrect)
Wrong path - /abc.cpp -> points to `hsc/abc.cpp`

**Expected behavior**
Expected path - ./abc.cpp -> points to `hsc/Hackerrank/Algorithms/Implementation/abc.cpp`

**Comment by rajatgoyal715** [comment]
Resolved in #17
