### ISSUE TITLE
Add more file extensions

### ISSUE THREAD

**Issue by rishabhsingh971** [Nullifiers/Hackerrank-Solution-Crawler#18]
More file extensions should be added in the crawler.

**Comment by rishabhsingh971** [comment]
Languages can be extracted from any challenge e.g https://www.hackerrank.com/rest/contests/master/challenges/solve-me-first/

**Comment by rajatgoyal715** [comment]
> Languages can be extracted from any challenge e.g https://www.hackerrank.com/rest/contests/master/challenges/solve-me-first/

@rishabh-smpx This link does not cover every language. I think it depends upon the problem like this one has SQL related languages.
https://www.hackerrank.com/rest/contests/master/challenges/revising-the-select-query/

How are we planning to tackle this problem?

**Comment by rishabhsingh971** [comment]
> > Languages can be extracted from any challenge e.g https://www.hackerrank.com/rest/contests/master/challenges/solve-me-first/
> 
> @rishabh-smpx This link does not cover every language. I think it depends upon the problem like this one has SQL related languages.
> https://www.hackerrank.com/rest/contests/master/challenges/revising-the-select-query/
> 
> How are we planning to tackle this problem?


We just have to add these languages too.
