### ISSUE TITLE
Config file(s)

### ISSUE THREAD

**Issue by rishabhsingh971** [Nullifiers/Hackerrank-Solution-Crawler#23]
A config file can be made to store different stuff like:
- username, password (after informing and taking permission from user)
- user settings
- last request time (to override old submission by a new one)
Also, metadata about each file downloaded can be stored in the same/different config.

**Comment by rajat19** [comment]
What you want to have in user settings ?

**Comment by rajat19** [comment]
Also,
how are we planning to store passwords ?
As it would be required to login user 
and we can't store it in old plain text

should we store some cookie instead ?

**Comment by rishabhsingh971** [comment]
> What you want to have in user settings ?

some/all of the inputs that can be configured by user (like username, limit, etc)

> should we store some cookie instead ?

storing cookie is a good idea
we can also cache the entire session. For that we can either manually pickle session or use https://github.com/rishabhsingh971/persession

**Comment by rajat19** [comment]
Other than storing cookie/session
everything else is covered in https://github.com/Nullifiers/Hackerrank-Solution-Crawler/pull/32

**Comment by rishabhsingh971** [comment]
> storing cookie is a good idea
> we can also can cache the entire session. For that we can either manually pickle session or use https://github.com/rishabhsingh971/persession

What do you think about this @rajat19 @rajatgoyal715?

**Comment by rajatgoyal715** [comment]
Yeah, sure. It looks like a good idea to me. But just one quick question - what's the expiration time of a cookie in general (like from hackerrank side)? Or there is no expiration time, like will the same cookie (which we'll save once) work every time till eternity?

**Comment by rishabhsingh971** [comment]
![image](https://user-images.githubusercontent.com/39947314/66713221-8196e180-edc5-11e9-88a1-ed155c68adbe.png)
From this, I guess expiration time is either 1 year or 1 week (if `remember_hacker_token` is considered). Maybe @rajat19 can enlighten us?

**Comment by rajatgoyal715** [comment]
@rishabhsingh971 You mean 2 weeks in case of `remember_hacker_token`?

**Comment by rishabhsingh971** [comment]
I meant 2 weeks, if `remember_hacker_token` has a role in keeping the user logged in.

**Comment by rajatgoyal715** [comment]
@rishabhsingh971 Can you please create a separate issue out of this? IMO we should have this discussion on the new issue, because this issue will be closed by #32
