### ISSUE TITLE
CLI flag support

### ISSUE THREAD

**Issue by rishabhsingh971** [Nullifiers/Hackerrank-Solution-Crawler#24]
User should be able to pass/set flags through CLI.

**Comment by rajatgoyal715** [comment]
@rishabhsingh971 Can you please be more specific about the flags here?

**Comment by rishabhsingh971** [comment]
Any kind of user input script requires, can be a flag just like user config as mentioned [here](https://github.com/Nullifiers/Hackerrank-Solution-Crawler/issues/23#issuecomment-538876434). This is so that script can become one liner instead of requiring user interaction multiple times.

**Comment by rishabhsingh971** [comment]
IMO, https://pypi.org/project/ConfigArgParse can help us solve both issues, #23 (only the user config) and #24
