### ISSUE TITLE
Progress bar to show running progress of crawler

### ISSUE THREAD

**Issue by rajatgoyal715** [Nullifiers/Hackerrank-Solution-Crawler#27]
### Problem:
Currently, the user has to wait for the completion of the crawler and then a message is displayed showing that "All solutions have been crawled".

### Solution:
It would be better if we can provide a progress bar showing the current progress of the number of solutions crawled.

#### Reference Link:
https://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console

**Comment by rajat19** [comment]
I have integrated progress bar in one of my other project https://github.com/rajat19/torrent-crawler
I would try to implement the same here

**Comment by rajatgoyal715** [comment]
Sure, go ahead :+1:

**Comment by rishabhsingh971** [comment]
> I have integrated progress bar in one of my other project https://github.com/rajat19/torrent-crawler
> I would try to implement the same here

Can you link the library used and/or code of progress bar in torrent-crawler, @rajat19

**Comment by rajat19** [comment]
No library used
Simple progrèss bar
See function update_progress in https://github.com/rajat19/torrent-crawler/blob/master/torrent_crawler/helper.py

Also the gif in readme of torrent-crawler shows how that progress bar would be working

**Comment by rajat19** [comment]
https://github.com/Nullifiers/Hackerrank-Solution-Crawler/pull/29

**Comment by rajatgoyal715** [comment]
@rajat19 Can we use something which has already been built and properly maintained like https://pypi.org/project/progress/
This will increase one dependency but will reduce much code.

**Comment by rajat19** [comment]
We can do that as well
It would just add additional dependency
Although it is good, and in future we can do modifications to our progress bar using its different suffices or different styles

**Comment by rajatgoyal715** [comment]
Correct, I also feel the same.
