### ISSUE TITLE
Allow crawler to fetch all solutions

### ISSUE THREAD

**Issue by rajatgoyal715** [Nullifiers/Hackerrank-Solution-Crawler#28]
### Problem
Currently, there is no feature to directly fetch all the solutions user have done.

### Solution
Firstly, we are fetching the total number of submissions user has done (to check whether login has been successful or not), so either we can show the number of submissions first, and then user can put the same number in the limit input to fetch all solutions.

On second thoughts, we can provide **limit** as a parameter to the script which will behave like this:
- If limit parameter is not passed, it will fetch all the submissions
- If limit parameter is passed, then it will fetch only that many solutions

@rajat19 @rishabhsingh971 Please provide your opinions on this.

**Comment by rajat19** [comment]
We can do something like this that includes both suggestions of yours -

```bash
You have total 345 submissions
Enter no. of submissions you want to download or press **Enter** instead to download all solutions
Limit:
Downloading all Solutions
```

**Comment by rajatgoyal715** [comment]
This is also fine. But the second option we have is like:
`python crawler.py --limit 200` will fetch limited submissions, and
`python crawler.py` will fetch all submissions.

And this seems to be a general way to me like all other packages have these parameters. Parameters list might add following in the future:
- `help` : list down all allowed parameters
- `offset` : get submissions after this offset
- `status_code` : crawl all submissions with this status_code
