### ISSUE TITLE
Problems in sorted order in Readme

### ISSUE THREAD

**Issue by rajat19** [Nullifiers/Hackerrank-Solution-Crawler#3]
Currently All Problems listed in Readme are in order of their being crawled
Change code so that they are in ascending order of the name of Problem

**Comment by siddhant-soni** [comment]
hey, i would like to take a shot at it

**Comment by rajatgoyal715** [comment]
Hey @siddhant-soni, you can go ahead.

**Comment by siddhant-soni** [comment]
please have a look at #5
