### ISSUE TITLE
Create root level and domain level README files

### ISSUE THREAD

**Issue by rajatgoyal715** [Nullifiers/Hackerrank-Solution-Crawler#39]
Currently, the script generates README files at the sub-domain level (Eg: Hackerrank/Algorithms/BitManipluation/). It'll be good if the script can similarly generate README files at root level (Hackerrank/) and domain level (Eg: Hackerrank/Algorithms/) as well.

**Comment by rajatgoyal715** [comment]
As part of this [comment](https://github.com/Nullifiers/Hackerrank-Solution-Crawler/pull/19#issuecomment-518015717), we wanted to expose one option to user to create a separate folder for the language inside subdomain folder, after which the structure will look something like `Hackerrank/Domain/Subdomain/Language/Problem.java`.
But as part of this issue, we wanted to create README files at every level, which means that we'll have to create one README at the language level also now if we want to support separate language folder.
Currently, I have made changes in PR: https://github.com/Nullifiers/Hackerrank-Solution-Crawler/pull/41 which supports README files at three levels: root level (Hackerrank), domain level (Eg: Algorithms) and subdomain level (Eg: BitManipulation).
@rishabhsingh971 @rajat19 Can you please help me out here to design such a system that can automatically generate README files at every layer we introduce in between? Or can we ignore the separate language folder feature for now?

**Comment by rishabhsingh971** [comment]
IMO We should not ignore it, but postpone it for now and make a separate issue out of this.
